INSERT INTO meals (id, meal_name, difficulty)
VALUES (1, "Teriyaki Chicken Hibachi", 3)
, (2, "Ramen", 1)
, (3, "BBQ Chicken Sandwiches", 1)
, (4, "Garlic Butter Noodles", 1)
, (5, "Spaghetti and Meatballs", 2)
, (6, "Chicken Quesadillas", 1)
, (7, "Grilled Chicken and Red Potatoes", 3)
, (8, "Bacon and Eggs", 2)
, (9, "Burgers and Fries", 3)
, (10, "Hibachi Rice", 2)


INSERT INTO ingredients (id, meals)
VALUES (1, "Teriyaki Chicken Hibachi", "chicken")
, (2, "Teriyaki Chicken Hibachi", "teriyaki sauce")
, (3, "Teriyaki Chicken Hibachi", "rice")
, (4, "Ramen", "ramen noodles")
, (5, "Ramen", "eggs")
, (6, "Ramen", "green onions")
, (7, "BBQ Chicken Sandwiches", "BBQ Chicken")
, (8, "BBQ Chicken Sandwiches", "buns")
, (9, "BBQ Chicken Sandwiches", "cheese")
, (10, "BBQ Chicken Sandwiches", "fries")
, (11, "Garlic Butter Noodles", "noodles")
, (12, "Garlic Butter Noodles", "butter")
, (13, "Garlic Butter Noodles", "garlic")
, (14, "Garlic Butter Noodles", "bacon")
, (15, "Garlic Butter Noodles", "parmesean cheese")
, (16, "Garlic Butter Noodles", "oregano")
, (17, "Spaghetti and Meatballs", "spaghetti")
, (18, "Spaghetti and Meatballs", "meatballs")
, (19, "Spaghetti and Meatballs", "marinara sauce")
, (20, "Spaghetti and Meatballs", "parmesean cheese")
, (21, "Chicken Quesadillas", "chicken")
, (22, "Chicken Quesadillas", "tortillas")
, (23, "Chicken Quesadillas", "cheese")
, (24, "Chicken Quesadillas", "salsa")
, (25, "Grilled Chicken and Red Potatoes", "chicken")
, (26, "Grilled Chicken and Red Potatoes", "red potatoes")
, (27, "Grilled Chicken and Red Potatoes", "butter")
, (28, "Grilled Chicken and Red Potatoes", "garlic")
, (29, "Grilled Chicken and Red Potatoes", "rosemary")
, (30, "Bacon and Eggs", "bacon")
, (31, "Bacon and Eggs", "eggs")
, (32, "Bacon and Eggs", "potato bread")
, (33, "Bacon and Eggs", "butter")
, (34, "Burgers and Fries", "beef")
, (35, "Burgers and Fries", "buns")
, (36, "Burgers and Fries", "cheese")
, (37, "Burgers and Fries", "fries")
, (38, "Burgers and Fries", "lettuce")
, (39, "Burgers and Fries", "onions")
, (40, "Hibachi Rice", "rice")








